config {
  type: "table",
  schema: "dvm",
  name: "link_users_trips",
  description: "users' trips link table",
  uniqueKey: ["user_trip_hash_id"],
  tags: ["data-vault"]
}

${
    dvform.get_link(
        models.users.columns,
        models.trips.columns,
        ref("src_trips"),
        ref("hub_users"),
        ref("hub_trips"),
        "user_hash_id",
        "trip_hash_id",
        "user_trip_hash_id"
    )
}
  