config {
  type: "table",
  schema: "dvm",
  name: "link_users_bikes",
  description: "users' bikes link table",
  uniqueKey: ["user_bike_hash_id"],
  tags: ["data-vault"]
}

${
    dvform.get_link(
        models.users.columns,
        models.bikes.columns,
        ref("src_trips"),
        ref("hub_users"),
        ref("hub_bikes"),
        "user_hash_id",
        "bike_hash_id",
        "user_bike_hash_id"
    )
}
  